### ISSUE TITLE
Tests stacktrace for phantom

### ISSUE THREAD

**Issue by pjpsoares** [madhukard/angular2-jspm-seed#12]
When I try to run the tests with Phantom and they fail, the stacktrace is kind of broken:

```
Expected undefined to equal ''.
        at :8
        at /Users/paulo/depot/personal/angular2-jspm-seed/node_modules/karma-jspm/src/adapter.js:61
        at /Users/paulo/depot/personal/angular2-jspm-seed/node_modules/babel-polyfill/dist/polyfill.js:3927
        at /Users/paulo/depot/personal/angular2-jspm-seed/node_modules/babel-polyfill/dist/polyfill.js:3940
        at /Users/paulo/depot/personal/angular2-jspm-seed/node_modules/babel-polyfill/dist/polyfill.js:1210
        at tryCatchReject (/Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:1188)
        at runContinuation1 (/Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:1147)
        at /Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:935
        at /Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:1045
        at /Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:102
        at /Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:67
    TypeError: 'undefined' is not a function (evaluating 'aboutComponent.onClickMe()')
        at :9
        at /Users/paulo/depot/personal/angular2-jspm-seed/node_modules/karma-jspm/src/adapter.js:61
        at /Users/paulo/depot/personal/angular2-jspm-seed/node_modules/babel-polyfill/dist/polyfill.js:3927
        at /Users/paulo/depot/personal/angular2-jspm-seed/node_modules/babel-polyfill/dist/polyfill.js:3940
        at /Users/paulo/depot/personal/angular2-jspm-seed/node_modules/babel-polyfill/dist/polyfill.js:1210
        at tryCatchReject (/Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:1188)
        at runContinuation1 (/Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:1147)
        at /Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:935
        at /Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:1045
        at /Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:102
        at /Users/paulo/depot/personal/angular2-jspm-seed/target/development/jspm/system-polyfills.src.js:67
```

and the same error in Chrome:

```
    Expected undefined to equal ''.
        at Object.eval (/Users/paulo/depot/personal/angular2-jspm-seed/target/development/src/about/about.spec.js:8:45)
    TypeError: aboutComponent.onClickMe is not a function
        at Object.eval (/Users/paulo/depot/personal/angular2-jspm-seed/target/development/src/about/about.spec.js:9:24)
```

**Comment by madhukard** [comment]
Not reproducible after updating to Angular 2 RC version
