### ISSUE TITLE
Javascript errors on fresh install

### ISSUE THREAD

**Issue by opsxcq** [madhukard/angular2-jspm-seed#6]
Aftera git clone, npm install and jspm install and success full running gulp.
Node 4.1, via nvm. JSPM 0.16.27. Gulp 3.9.0. NPM 2.14.4
I got this error accessing the page, (the error shows on javascript console)

EXCEPTION: TypeError: o.addTask is not a function
browser_adapter.js:81 EXCEPTION: TypeError: o.addTask is not a functionBrowserDomAdapter.logError @ browser_adapter.js:81BrowserDomAdapter.logGroup @ browser_adapter.js:92ExceptionHandler.call @ exception_handler.js:53(anonymous function) @ application_ref.js:158NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156e.run @ angular2-polyfills.min.js:1(anonymous function) @ ng_zone.js:175(anonymous function) @ angular2-polyfills.min.js:1e.run @ angular2-polyfills.min.js:1(anonymous function) @ ng_zone.js:175(anonymous function) @ angular2-polyfills.min.js:1x @ angular2-polyfills.min.js:1F @ angular2-polyfills.min.js:1A @ angular2-polyfills.min.js:1O @ angular2-polyfills.min.js:1(anonymous function) @ angular2-polyfills.min.js:1microtask @ ng_zone.js:207e.run @ angular2-polyfills.min.js:1(anonymous function) @ ng_zone.js:175(anonymous function) @ angular2-polyfills.min.js:1y @ angular2-polyfills.min.js:1
browser_adapter.js:81 STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:81ExceptionHandler.call @ exception_handler.js:55(anonymous function) @ application_ref.js:158NgZone._notifyOnError @ ng_zone.js:252collection_1.StringMapWrapper.merge.onError @ ng_zone.js:156e.run @ angular2-polyfills.min.js:1(anonymous function) @ ng_zone.js:175(anonymous function) @ angular2-polyfills.min.js:1e.run @ angular2-polyfills.min.js:1(anonymous function) @ ng_zone.js:175(anonymous function) @ angular2-polyfills.min.js:1x @ angular2-polyfills.min.js:1F @ angular2-polyfills.min.js:1A @ angular2-polyfills.min.js:1O @ angular2-polyfills.min.js:1(anonymous function) @ angular2-polyfills.min.js:1microtask @ ng_zone.js:207e.run @ angular2-polyfills.min.js:1(anonymous function) @ ng_zone.js:175(anonymous function) @ angular2-polyfills.min.js:1y @ angular2-polyfills.min.js:1
browser_adapter.js:81 TypeError: o.addTask is not a function
    at n.(anonymous function) (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:14721)
    at e.setTimeout (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/core/zone/ng_zone.js:227:18)
    at e.(anonymous function) (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:14322)
    at WS.write (http://10.1.1.8:3000/browser-sync/browser-sync-client.2.11.1.js:2:12303)
    at WS.Transport.send (http://10.1.1.8:3000/browser-sync/browser-sync-client.2.11.1.js:1:30343)
    at Socket.flush (http://10.1.1.8:3000/browser-sync/browser-sync-client.2.11.1.js:1:26893)
    at Socket.sendPacket (http://10.1.1.8:3000/browser-sync/browser-sync-client.2.11.1.js:1:27335)
    at Socket.write.Socket.send (http://10.1.1.8:3000/browser-sync/browser-sync-client.2.11.1.js:1:27047)
    at http://10.1.1.8:3000/browser-sync/browser-sync-client.2.11.1.js:1:6684
    at Encoder.encode (http://10.1.1.8:3000/browser-sync/browser-sync-client.2.11.1.js:3:10535)

-----async gap-----
Error
    at r (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:22053)
    at e.fork (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:22994)
    at e.bind (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:8338)
    at r (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:10985)
    at $.t.(anonymous function) [as catch](http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:11095)
    at Function.PromiseWrapper.catchError (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/facade/promise.js:12:29)
    at RootRouter.Router._afterPromiseFinishNavigating (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/router/router.js:172:35)
    at http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/router/router.js:112:20
    at e.run (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:8725)

-----async gap-----
Error
    at r (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:22053)
    at e.fork (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:22994)
    at e.bind (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:8338)
    at r (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:10985)
    at $.t.(anonymous function) [as then](http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:11095)
    at RootRouter.Router.navigateByUrl (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/router/router.js:109:62)
    at new RootRouter (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/router/router.js:339:10)
    at routerFactory (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/router.js:61:20)
    at Injector._instantiate (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/core/di/injector.js:508:19)
    at Injector._instantiateProvider (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/core/di/injector.js:438:21)

-----async gap-----
Error
    at r (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:22053)
    at e.fork (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:22994)
    at e.bind (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:8338)
    at r (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:10985)
    at $.t.(anonymous function) [as then](http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:11095)
    at DynamicComponentLoader_.loadAsRoot (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/core/linker/dynamic_component_loader.js:88:47)
    at di_1.provide.useFactory (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/core/application_ref.js:29:37)
    at Injector._instantiate (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/core/di/injector.js:505:19)
    at Injector._instantiateProvider (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/core/di/injector.js:438:21)
    at Injector._new (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/core/di/injector.js:428:19)

-----async gap-----
Error
    at r (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:22053)
    at e.fork (http://10.1.1.8:3000/vendor/angular2-polyfills.min.js:1:22994)
    at createNgZone (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/core/application_ref.js:50:10)
    at PlatformRef_.application (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/src/core/application_ref.js:125:29)
    at Object.bootstrap (http://10.1.1.8:3000/jspm/npm/angular2@2.0.0-beta.0/platform/browser.js:29:64)
    at Object.<anonymous> (http://10.1.1.8:3000/src/boot.js:12:11)
    at http://10.1.1.8:3000/src/boot.js:14:4
    at l.$ (http://10.1.1.8:3000/jspm/system.js:4:18033)

**Comment by madhukard** [comment]
I too got that error message when using angular2 version 2.0.0-beta.2. They have fixed that issue in angular2@2.0.0-beta.3 version

https://github.com/angular/angular/blob/master/CHANGELOG.md
zone: correct incorrect calls to zone (3211938)

**Comment by opsxcq** [comment]
Fixed on beta 3. Everything is fine now
